title: My GitHub Page
description: A simple GitHub Pages site with Jekyll
url: https://samorep.si
baseurl: ""
# Add GitHub Pages repository settings
repository: samorep/samorep.si # Replace USERNAME with your GitHub username
# Keep the minima theme which is GitHub Pages compatible
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-github-metadata

# Added GitHub Pages defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

# Exclude specific files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/ 