title: My GitHub Page
description: A simple GitHub Pages site with Jekyll
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
search: false

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Site Author
author:
  name: "Your Name"
  bio: "A short bio about yourself."
  location: "Location"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true 